<map version="0.9.0_Beta_8">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node COLOR="#000000" CREATED="1196208667679" ID="Freemind_Link_372183106" MODIFIED="1200851367935" STYLE="bubble">
<richcontent TYPE="NODE"><html>
  <head>
    <style type="text/css">
      <!--
        p { margin-top: 0 }
      -->
    </style>
        
  </head>
  <body>
    <p style="text-align: center">
      To what extent do
    </p>
    <p style="text-align: center">
      <b>social, </b>
    </p>
    <p style="text-align: center">
      <b>peer-2-peer or participatory </b>
    </p>
    <p style="text-align: center">
      financial models democratize capital?
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="20"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties"/>
<node COLOR="#0033ff" CREATED="1196208723305" HGAP="142" ID="Freemind_Link_863167236" MODIFIED="1200873177036" POSITION="right" TEXT="themes" VSHIFT="12">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      what are the principle themes that are problemitised by this question?
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1200873198545" ID="Freemind_Link_1530732472" MODIFIED="1200873212505" TEXT="using banking to examine capital / capitalism">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1196208731224" ID="Freemind_Link_471704442" MODIFIED="1200873220283" TEXT="nature of captialism">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      Is capitalism inherently undemocratic? even anti-democratic? To what extent can capitalism be democratic?
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1196208736582" ID="Freemind_Link_1034204962" MODIFIED="1200873220285" TEXT="economic democracy">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      to what extent can the economy be democratic? here I am thinking both in terms of government regulation and in terms of access to services.
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
<node COLOR="#990000" CREATED="1196209215074" ID="Freemind_Link_704087676" MODIFIED="1200873226440" TEXT="private banking; a system creating money from debt">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1196209223101" ID="Freemind_Link_1912651393" MODIFIED="1200873226441" TEXT="the making of money from money?">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1196209229789" ID="Freemind_Link_464695027" MODIFIED="1200873226445" TEXT="risk profiling">
<font NAME="SansSerif" SIZE="12"/>
</node>
<node COLOR="#111111" CREATED="1196209237606" ID="Freemind_Link_450166085" MODIFIED="1200873226447" TEXT="credit scoring">
<font NAME="SansSerif" SIZE="12"/>
</node>
</node>
</node>
<node COLOR="#00b439" CREATED="1196208743869" ID="Freemind_Link_1063658156" MODIFIED="1200873177053" TEXT="social lending">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1196209099582" ID="Freemind_Link_728692434" MODIFIED="1200851367884" TEXT="co-operatives, mutual socities, building socities">
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1196209131911" ID="Freemind_Link_1176767103" MODIFIED="1200851367885" TEXT="credit worthiness; risk profiling">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      here I am thinking more about `sub-prime mortgages' and low income households
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1200861729017" ID="Freemind_Link_1819531718" MODIFIED="1200873177061" TEXT="money and markets (rather than capitalism)">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      Keith Hart - &quot;Markets and money are necessary for the extension of human society, but their contemporary impersonal form is unsustainable. The kula valuables [inter-tribal gifts] might well be considered a form of personal money. Capitalist institutions too combine self-interest and elements of the gift; and sociologists should make this more visible, while rejecting the one-sided accounts generated by capitalism&#8217;s apologists and detractors alike.&quot; Money SGV
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1196208749018" ID="Freemind_Link_93449305" MODIFIED="1200873177061" POSITION="left" TEXT="case studies">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      case studies of `social' financial models
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1196208751837" ID="Freemind_Link_1580243056" MODIFIED="1200873177061" TEXT="zopa">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      p2p lending, mediated risk, credit scoring...
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1196210589787" ID="Freemind_Link_1474644331" MODIFIED="1200851367891">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p>
      a virtualisation of the good old savings and loan
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="14"/>
<node COLOR="#111111" CREATED="1196210478297" ID="Freemind_Link_1110063024" MODIFIED="1200851367893" TEXT="provision of a service only as business model, virtualised businesses, customer driven"/>
<node COLOR="#111111" CREATED="1196209708181" ID="Freemind_Link_1186729869" MODIFIED="1200851367894" TEXT="horizontal structure"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1200860998483" ID="Freemind_Link_260160811" MODIFIED="1200873177063" TEXT="kiva">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      peer2peer international development finance
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
<node COLOR="#00b439" CREATED="1196209864859" ID="Freemind_Link_1557155184" MODIFIED="1200873177063" TEXT="open capital">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      the ideas of chris cook demonstrate that participatory economics can scales to infrastrucutre projects of a significant size.
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1196209870377" ID="Freemind_Link_1543231373" MODIFIED="1200851367894" TEXT="chris cook">
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1196209873487" ID="Freemind_Link_1111896659" MODIFIED="1200851367895" TEXT="Limited Liability Partnership model for community infrastructre projects">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
</node>
<node COLOR="#0033ff" CREATED="1196209297936" HGAP="155" ID="Freemind_Link_76104970" MODIFIED="1200873177064" POSITION="right" TEXT="relationship to NRPE" VSHIFT="-50">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      Where is this problem positioned in terms of New Radical Political Economy?
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1196208906865" ID="Freemind_Link_1251576177" MODIFIED="1200873177064" TEXT="undemocratic financial institutions">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      lack of transparency; impersonal relationships, dehumanised, systematised; restrictions on access; structural (credit scoring) exclusion from services
    </p>
    <p>
      further criticisms of banking institutions and debt money at international level
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1196208916922" ID="Freemind_Link_1422245583" MODIFIED="1200851367900" TEXT="banking as a service">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      technology; why don't states provide banking services?
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1196209324228" ID="Freemind_Link_995207325" MODIFIED="1200851367901" TEXT="scale - p2p at World Bank tier of economy?">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      does this scale?
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1196209408520" ID="Freemind_Link_1473525571" MODIFIED="1200873177065" TEXT="money">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1196208894229" ID="Freemind_Link_1753529451" MODIFIED="1201446091778" TEXT="monetary reform">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      anti-capitalist in the dialectical marxist sense; in search of monetary reform as pragmatist
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1196208900967" ID="Freemind_Link_1744831623" MODIFIED="1200851367903" TEXT="debt free money">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1200851719378" ID="Freemind_Link_451096282" MODIFIED="1200873177066" TEXT="anti-corporation critique">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1196210382669" HGAP="18" ID="Freemind_Link_512073600" MODIFIED="1200873177067" POSITION="left" VSHIFT="34">
<richcontent TYPE="NODE"><html>
  <head>
    <style type="text/css">
      <!--
        p { margin-top: 0 }
      -->
    </style>
        
  </head>
  <body>
    <p>
      what do I mean by...
    </p>
  </body>
</html>
</richcontent>
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1200851745826" ID="Freemind_Link_263671377" MODIFIED="1200873177069" TEXT="social, p2p/participatory">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1196210407573" HGAP="21" ID="Freemind_Link_1534642584" MODIFIED="1201446031349" TEXT="an appropiration of `Web 2.0&apos; jargon" VSHIFT="-10">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      neologism?
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1196210657598" HGAP="24" ID="Freemind_Link_589071581" MODIFIED="1201446034020" VSHIFT="9">
<richcontent TYPE="NODE"><html>
  <head>
    <style type="text/css">
      <!--
        p { margin-top: 0 }
      -->
    </style>
        
  </head>
  <body>
    <p>
      <i>genuine</i> savings and loan reform
    </p>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1200851751810" ID="Freemind_Link_673364062" MODIFIED="1200873343023" TEXT="democratise">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1201448714758" ID="Freemind_Link_1792523290" MODIFIED="1201448733421" TEXT="people making their own decisions">
<font NAME="SansSerif" SIZE="14"/>
</node>
<node COLOR="#990000" CREATED="1201448734466" ID="Freemind_Link_855292737" MODIFIED="1201448739597" TEXT="opening of access">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1200873343971" ID="Freemind_Link_1321042358" MODIFIED="1200873345962" TEXT="capital">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1200671685895" HGAP="144" ID="Freemind_Link_405448290" MODIFIED="1200873177077" POSITION="right" TEXT="people to read" VSHIFT="-56">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1200671691015" ID="Freemind_Link_950213218" MODIFIED="1200873177078" TEXT="Karl Polanyi">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
<node COLOR="#00b439" CREATED="1200671695799" ID="Freemind_Link_683409628" MODIFIED="1200873177079" TEXT="Keith Hart">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
<node COLOR="#990000" CREATED="1200861865051" ID="Freemind_Link_1917696152" MODIFIED="1200861877351" TEXT="tries to separate the idea of &#x2018;markets&#x2019; and &#x2018;money&#x2019; from their association with &#x2018;capitalism&#x2019; - Money SGV">
<font NAME="SansSerif" SIZE="14"/>
</node>
</node>
<node COLOR="#00b439" CREATED="1202072280500" ID="Freemind_Link_680436465" LINK="http://en.wikipedia.org/wiki/John_Kenneth_Galbraith" MODIFIED="1202072297450" TEXT="John Kenneth Galbraith">
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
<node COLOR="#0033ff" CREATED="1200861683161" HGAP="21" ID="Freemind_Link_191658113" MODIFIED="1200873353189" POSITION="left" TEXT="approach" VSHIFT="24">
<edge STYLE="sharp_bezier" WIDTH="8"/>
<font NAME="SansSerif" SIZE="18"/>
<node COLOR="#00b439" CREATED="1200861706778" ID="Freemind_Link_1417765665" MODIFIED="1200873177082" TEXT="don&apos;t be one-sided!">
<edge STYLE="bezier" WIDTH="thin"/>
<font NAME="SansSerif" SIZE="16"/>
</node>
</node>
</node>
</map>
